### ISSUE TITLE
error: narrowing conversion with gcc 6

### ISSUE THREAD

**Issue by mjbogusz** [rapp-project/rapp-robots-api#12]
Log:

```
[...]/rapp-robots-api/cpp/implementations/vision.cpp:61:49: error: narrowing conversion of 137 from int to rapp::types::byte {aka char} inside { } [-Wnarrowing]
         rapp::types::byte bytes[2] = {0x89, 0x50};
                                                 ^
```

Simple inline fix:
replace `0x89` with `static_cast<char>(0x89)`

**Comment by etsardou** [comment]
Is this fixed? Should it be closed?

**Comment by mjbogusz** [comment]
Yes, by 08bbe0000f922f8e7474d23de16d9a610b74a318 it seems.

Even if `(char) 0x89` is a bit less change-proof and platform-independent (or just less fancy), than `static_cast<rapp::types::byte>(0x89)`.
Not mentioning the fact that [the type itself](https://github.com/rapp-project/rapp-api/blob/master/cpp/includes/objects/globals.hpp) could (should?) rather be declared as an unsigned int or even uint8_t.
